import type { CandidateRepoConfigChangeType } from "../agents/state";
import type { RepoConfigSecurityIssue } from "../config/repo-config-security";

export interface ConfigSecurityNoteRecord {
  id: number;
  body: string;
}

export interface ConfigSecurityNoteOptions {
  candidateChangeType?: CandidateRepoConfigChangeType;
  candidateRepoConfigBytes?: number | null;
  deterministicOnly?: boolean;
  securitySummary?: string;
}

export const CONFIG_SECURITY_MARKER = "<!-- code-smith:config-security -->";
export const CONFIG_SECURITY_HEAD_MARKER_PREFIX = "<!-- code-smith:config-security head sha=";

const MAX_NOTE_CHARS = 6_000;
const MAX_ISSUES = 8;
const MAX_EXCERPT_CHARS = 160;

function escapeConfigSecurityText(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("```", "`&#96;&#96;")
    .replaceAll("code-smith:", "code-smith&#58;");
}

function capText(value: string, maxChars: number): string {
  return value.length > maxChars ? `${value.slice(0, maxChars - 3)}...` : value;
}

function formatCandidateChangeType(changeType: CandidateRepoConfigChangeType | undefined): string {
  switch (changeType) {
    case "added":
      return "Candidate repo config was added in this MR.";
    case "modified":
      return "Candidate repo config differs from the trusted target-branch baseline.";
    case "removed":
      return "Candidate repo config was removed in this MR; the review still used the trusted target-branch baseline.";
    case "unchanged":
      return "Candidate repo config matches the trusted target-branch baseline.";
    default:
      return "Candidate repo config was screened separately from the trusted target-branch baseline.";
  }
}

function formatIssue(issue: RepoConfigSecurityIssue): string {
  const evidence = capText(escapeConfigSecurityText(issue.evidence), MAX_EXCERPT_CHARS);
  const suggestion = capText(escapeConfigSecurityText(issue.suggestion), MAX_EXCERPT_CHARS);
  const message = escapeConfigSecurityText(issue.message);

  return [
    `### ${issue.fieldPath}`,
    `- Severity: ${issue.severity}`,
    `- Category: ${issue.category}`,
    `- Action: ${issue.action}`,
    `- Message: ${message}`,
    `- Evidence: ${evidence}`,
    `- Suggested fix: ${suggestion}`,
  ].join("\n");
}

export function findExistingConfigSecurityNote(
  notes: ConfigSecurityNoteRecord[],
  headSha: string,
): ConfigSecurityNoteRecord | null {
  if (!headSha) {
    return null;
  }

  const headMarker = `${CONFIG_SECURITY_HEAD_MARKER_PREFIX}${headSha} -->`;
  return notes.find((note) => note.body.includes(CONFIG_SECURITY_MARKER) && note.body.includes(headMarker)) ?? null;
}

export function formatConfigSecurityNote(
  headSha: string,
  issues: RepoConfigSecurityIssue[],
  options: ConfigSecurityNoteOptions = {},
): string {
  const metadataLines = [
    formatCandidateChangeType(options.candidateChangeType),
    `The current review continued under the trusted target-branch baseline config, not the candidate config from this MR.`,
  ];

  if (typeof options.candidateRepoConfigBytes === "number") {
    metadataLines.push(`Candidate config size: ${options.candidateRepoConfigBytes} bytes.`);
  }

  if (options.deterministicOnly) {
    metadataLines.push(`Deterministic-only mode is enabled for config screening.`);
  }

  if (options.securitySummary?.trim()) {
    metadataLines.push(`Security summary: ${escapeConfigSecurityText(capText(options.securitySummary.trim(), 200))}`);
  }

  const issueBlocks: string[] = [];
  let renderedIssues = 0;

  for (const issue of issues.slice(0, MAX_ISSUES)) {
    const candidateBlock = formatIssue(issue);
    const nextBlocks = [...issueBlocks, candidateBlock];
    const candidateBody = [
      CONFIG_SECURITY_MARKER,
      "## CodeSmith Repo Config Security",
      "",
      ...metadataLines,
      "",
      `Detected ${issues.length} repo-config security finding(s).`,
      "",
      ...nextBlocks,
      "",
      `${CONFIG_SECURITY_HEAD_MARKER_PREFIX}${headSha} -->`,
      "",
      "---",
      "_Config-security note generated by [CodeSmith](https://github.com/elis-salobehaj/code-smith)_",
    ].join("\n");

    if (candidateBody.length > MAX_NOTE_CHARS) {
      break;
    }

    issueBlocks.push(candidateBlock);
    renderedIssues++;
  }

  const lines = [
    CONFIG_SECURITY_MARKER,
    "## CodeSmith Repo Config Security",
    "",
    ...metadataLines,
    "",
    `Detected ${issues.length} repo-config security finding(s).`,
    "",
    ...issueBlocks,
  ];

  if (renderedIssues < issues.length) {
    lines.push(
      "",
      `Additional findings were omitted to keep the note within the publication size cap (${renderedIssues}/${issues.length} shown).`,
    );
  }

  lines.push(
    "",
    `${CONFIG_SECURITY_HEAD_MARKER_PREFIX}${headSha} -->`,
    "",
    "---",
    "_Config-security note generated by [CodeSmith](https://github.com/elis-salobehaj/code-smith)_",
  );

  return lines.join("\n");
}
